#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GnomeCanvas
version:      0.25
version_from: Canvas.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
