#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gnome2-Canvas
version:      1.002
version_from: Canvas.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
